### ISSUE TITLE
Determine specific guidance for trajectory_id variable.

### ISSUE THREAD

**Issue by dpsnowden** [IOOSProfilingGliders/Real-Time-File-Format#1]
See the [discussion](https://github.com/IOOSProfilingGliders/Real-Time-File-Format/wiki/Real-Time-File-Description#the-trajectory-feature-type) on the wiki page outlining the problem and a couple options.  This isn't exhaustive.  How specific do we need to be on the usage of this variable in order to get the desired THREDDS aggregation behavior?

**Comment by dpsnowden** [comment]
Perform a test.  Create two files representing two segments of the same deployment.  In file A set trajectory=1, in file B set trajectory= 2.  Aggregate both as a single deployment along time.  Test how THREDDS performs.  Next, do the same thing but this time setting both trajectory=1.  Does the returned data set look identical in both cases?

**Comment by kerfoot** [comment]
As per discussion with dpsnowden, we agree that the terms 'trajectory' and 'deployment' are synonyms.  Will perform test described in https://github.com/IOOSProfilingGliders/Real-Time-File-Format/issues/1#issuecomment-21811826 with ASA.

**Comment by kwilcox** [comment]
We decided to always set this to 1.
