### ISSUE TITLE
QC flag variables for coordinate variables

### ISSUE THREAD

**Issue by kerfoot** [IOOSProfilingGliders/Real-Time-File-Format#6]
Not sure if this was an oversite on my part (or intentional), but I'd like to add QC flag variables for the 'time' and 'time_uv' variables.  At a minimum, I need flag values of 'measured' and 'interpolated'.  I'm not sure about the spray or seaglider, but the sampling configurability of the slocum glider allows for missing timestamp values which are allowed for coordinate variables.  So I'd like to fill the missing values and use the _qc variables to denote this.

Any problem with interpolating missing values in the coordinate array?

**Comment by dpsnowden** [comment]
If you've verified that this is legal CF behavior then I see no reason not to do it.  I would first check with the GROOM manual.  If I recall they have a pretty clear way of specifying how a variable is created and that it is general enough to apply to all variables.  Similar to the measured vs interpolated.

Another source of information we should probably include is the ACDD proposed variable attribute `coverage_content_type`.  This attribute uses ISO 19115 code spaces to indicate how the variable was derived.  Check out the discussion at the [ACDD page](http://wiki.esipfed.org/index.php/Attribute_Convention_for_Data_Discovery_%28ACDD%29#Highly_Recommended).
